version: "3.9"

services:
  api:
    build: .
    container_name: api
    ports:
      - "80:8000"
    environment:
      DB_HOST: user
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: stock
    restart: unless-stopped
